[package]
name = "revive-builtins"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
build = "build.rs"
description = "compiler builtins for the revive compiler"

[features]
riscv-64 = []

[dependencies]
