[package]
name = "revive-stdlib"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
description = "revive compiler stdlib components"

[dependencies]
inkwell = { workspace = true, features = ["target-riscv", "no-libffi-linking", "llvm18-0"] }
