[package]
name = "revive-integration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polkavm = { workspace = true }
alloy-primitives = { workspace = true }
parity-scale-codec = { workspace = true }
revive-solidity = { path = "../solidity" }
era-compiler-llvm-context = { path = "../llvm-context" }
hex = { workspace = true }
env_logger = { workspace = true }

[dev-dependencies]
alloy-sol-types = { workspace = true }
sha1 = { workspace = true }
