[target.wasm32-unknown-emscripten]
rustflags = [
    "-Clink-arg=-sEXPORTED_FUNCTIONS=_main,_free,_malloc",
    "-Clink-arg=-sNO_INVOKE_RUN=1",
    "-Clink-arg=-sEXIT_RUNTIME=1",
    "-Clink-arg=-sALLOW_MEMORY_GROWTH=1",
    "-Clink-arg=-sEXPORTED_RUNTIME_METHODS=FS,callMain,stringToNewUTF8",
    "-Clink-arg=-sWASM_ASYNC_COMPILATION=0",
    "-Clink-arg=--extern-pre-js=js/emscripten/embed/extern-pre.js",
    "-Clink-arg=--extern-post-js=js/emscripten/embed/extern-post.js",
    "-Clink-arg=-sDYNAMIC_EXECUTION=0",
    "-Clink-arg=-sALLOW_TABLE_GROWTH=1",
    "-Clink-arg=--js-library=js/emscripten/embed/soljson_interface.js",
    "-Clink-arg=--pre-js=js/emscripten/embed/pre.js",
    "-Clink-arg=-sSTACK_SIZE=128kb",
    "-Clink-arg=-sNODEJS_CATCH_EXIT=0"
]

[build]
rustdocflags = ["-D", "warnings"]
