[package]
name = "revive-build-utils"
version = "1.0.0"
license.workspace = true
edition.workspace = true
repository.workspace = true
authors = [
    "Cyrill Leutwiler <cyrill@parity.io>",
]
description = "Shared build utilities of the revive compiler"

[lib]
doctest = false

[dependencies]
